### ISSUE TITLE
Separators that conflict with regex special characters do not work

### ISSUE THREAD

**Issue by brentyates** [opendatasoft/elasticsearch-aggregation-pathhierarchy#1]
Hi, first off, I love the idea of this plugin. Until one day hopefully elasticsearch incorporates it as a core aggregation, it is exactly what I need.

However, I have found that our separator, the "|" symbol, does not work properly because the separator string is passed straight to the java string split function, which accepts a regex string (the "|" would normally need to be escaped).

Passing the separator already-escaped via the API does not work either; there are other sections of the code that interpret the separator as a regular string, therefore the escape characters become part of the separator in those scenarios.

My proposed solution would be to not use the default java string.split, but rather some method that splits on the raw string, so that the input is always simply interpreted as is. 

I can code the solution, but is this something you would be interested in accepting a pull request for so that everybody gets the fix? Or should I simply fork the plugin.

Thanks!

**Comment by clement-tourriere** [comment]
Hi, 
thank you very much for your review.
I think the proper solution would be to used Pattern.quote method (http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#quote%28java.lang.String%29).

I'm fixing it right now.

**Comment by brentyates** [comment]
Thanks for the super fast turnaround @clement-tourriere, this is awesome! I'll try it out but the approach looks right and your unit test even uses my symbol, I am confident it will work, you even used my separator in your unit test :+1: Thanks a million!
