### ISSUE TITLE
Need some help to use this plug-in with Elasticsearch minor update 7.4.2

### ISSUE THREAD

**Issue by sshah-biz** [opendatasoft/elasticsearch-aggregation-pathhierarchy#14]
Thank you for the good application.

I know this plugin available for ES version 7.4.0 only.

Just curious is there any way this could be available for ES version 7.4.2.
As I am not able to install this plugin on es 7.4.2 with following error.....
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [pathhierarchy-aggregation] was built for Elasticsearch version 7.4.0 but version 7.4.2 is running

The reason for me to check on this is we have to update the ES from 7.4.0 to 7.4.2 to get other feature fixed/updated.

-Sanjay

**Comment by clement-tourriere** [comment]
Hi,
I've updated the code, the release will be available soon.

**Comment by sshah-biz** [comment]
Thank you for the help I will try to look for it after few hours.
Please let me know from where can i get detail for the download plugin URL if it is different then the  code page URL (https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy) README.md as the last row in the table.

Thank you,
Sanjay

**Comment by sshah-biz** [comment]
By the way is there any update for me to download plugin URL for 7.4.2.
I do see that PR is created 8 days ago.

Please advice in case I have to do on my side to download proper plugin.,

Thank you again for all the help.
-Sanjay

**Comment by 5k4nd** [comment]
Hi @sshah-biz,

Thank you for your interest in our plugin. You'll find the 7.4.2 plugin .zip release here: https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/download/v7.4.2.0/pathhierarchy-aggregation-7.4.2.0.zip

Have a nice day,
Regards
