### ISSUE TITLE
Need support for Elasticsearch version 7.8.x

### ISSUE THREAD

**Issue by sshah-biz** [opendatasoft/elasticsearch-aggregation-pathhierarchy#18]
We are using this plugin extensively in our code.
At this time is is supporting Elasticsearch Release version 7.6.0, we need to use this for version 7.8.x.
May I request to create this plugin version for 7.8.0 and 7.8.1.

Your quick help will be appreciated.

Thank you,
Sanjay

**Comment by sshah-biz** [comment]
Friendly reminder.....
May I request to add the plugin version to support 7.9.0 and 7.9.3 as well.

Your quick help will be appreciated.

Thank you,
Sanjay

**Comment by sshah-biz** [comment]
Please keep us update when will we have the plugin version 7.9.0 and 7.9.3 along with 7.8.0 and 7.8.1.
I appreciate all your help to get this plugin at earliest.

Thank you,
Sanjay

**Comment by thoumasd** [comment]
Dear Sanjay,

I'm really sorry for the late answer as we've been quite busy lately.

We are definitely committed to follow the releases of ES trunk for the plugins we maintain, unless explicitly stated.

We should update this one in the coming months and we'll get back to you as we move forward.

Thank you for your patience,

Best regards,

David

**Comment by sshah-biz** [comment]
Hello David,
Thank you very much for acknowledging it. 
I really appreciate.

May I ask you one more favor, if you know any tentative date to release the pending ES truck for this plugins.

The reason to ask you so that I can keep my executive informed for the better planning.

Thank you again
-Sanjay

**Comment by thoumasd** [comment]
Dear Sanjay,

Unfortunately, there's no certainty regarding the release date as of now.

As we make progress on this, be sure we will inform you.

Best regards,

David

**Comment by sshah-biz** [comment]
Hello David,
Thank you for reply.
Good luck on creating the release version matching ES version.
Please keep us inform, will be waiting to hear from you at earliest.

Thank you,
-Sanjay

**Comment by sshah-biz** [comment]
Hello David,
Friendly reminder.

Kindly keep me inform once any progress made on this request of creating the release version matching ES version.
IN case if you need any thing my side, please keep me inform.

Thank you,
-Sanjay

**Comment by sshah-biz** [comment]
Hello David,
Wish you Happy New Year.

Friendly reminder.

As of now not heard any thing on this issue, do you think you will able to provide any resolution for this issue OR it is not in your planning to provide any more release. If it is in your planning to provide resolution then kindly keep us inform with expected release date.

Your answer will be appreciated.

-Sanjay

**Comment by thoumasd** [comment]
Hello Sanjay,

Thank you for your message and I wish you as well a happy new year!

It's definitely in our plans to provide releases for more recent versions of Elasticsearch but we are focusing on other projects for now so, I cannot provide you with release date options. Feel free to fork the project and adapt it to more recent versions of ES if your need is urgent.

We will anyway inform you as we make progress on our side on this topic.

Best regards,

David

**Comment by sshah-biz** [comment]
Thank you David for your message.
Good luck on your projects on hand.

-Sanjay

**Comment by cchyung** [comment]
Hi David, any further updates on supporting this package for 7.(x >= 8).x?

**Comment by benj-moreau** [comment]
Hi @cchyung @sshah-biz,

We are currently releasing plugin for ES versions 7.10.2, 7.16.3 and 7.17.0 and do not plan to support other versions for the moment.
I hope these versions will meet your needs.

Regards,

Benjamin.
