### ISSUE TITLE
Performance with large data sets

### ISSUE THREAD

**Issue by kutenai** [opendatasoft/elasticsearch-aggregation-pathhierarchy#2]
This is not an issue so much as a question.

This plugin works exactly as described. For data-sets with a few hundred thousand entries, performance is fine. As the # of entries increases, I see it slowing down approximately linearly (which I expected). 

For ~ 1 million records, it takes about ~ 3 seconds to return a result. At 1.4 million, ~ 4.6 seconds, etc. I did a very quick look at the code, and it appears it must iterate over all returned records and re-categorize them using the path.

Do you have any thoughts on ways to improve performance? Some obvious things are:
- caching. This works great at the 'top' level with no other search terms, but becomes less useful as search terms are introduced.

One question I have is, do you see a way to query just a particular level? I've used the 'max_depth' option, but this does not seem to help with performance. It decreases the overall time some, but not significantly. With 1.5M records, the query time goes from > 5 seconds, to 3.5seconds. My gut feeling is that there isn't a way around this, as the counts still require looking at all items in order to summarize.

Thanks for a great module, and any thoughts you have on this question.

**Comment by clement-tourriere** [comment]
First of all thank you so much for your review.

There is indeed a performance issue with the current implementation. 
I have fixed it and query time seems better now (70 ms for 1 million). I will release that really soon with another little optimizations.

Thank you again for your report ;)

**Comment by kutenai** [comment]
Wow.. 70ms/1M records.. that is quite impressive! Right now I am seeing 
11seconds with 3.7M records, so that is a really huge improvement!!
