### ISSUE TITLE
Support for ES version 6.8.10

### ISSUE THREAD

**Issue by inxss** [opendatasoft/elasticsearch-aggregation-pathhierarchy#20]
Hi,
Which version of the plugin would work with the ES version 6.8.10? 
I tried to install v7.0.0.0 but it failed due to version incompatibility. 
Thanks, 
Vikram.

**Comment by benj-moreau** [comment]
Hi @inxss,

Unfortunately, we do not support ES version 6.8.10 and we do not plan to support it for the moment.
We are currently releasing the plugin for ES version 7.X maybe one of these version suit your needs.
If not, feel free to fork the 6.8.2 version and adapt it to 6.8.10.

Best regards,

Benjamin.
