### ISSUE TITLE
Request for a Java 11 compatible build

### ISSUE THREAD

**Issue by nescalera** [opendatasoft/elasticsearch-aggregation-pathhierarchy#24]
Hi guys,

We are upgrading our ES server from 7.5.1 to v7.17.1. Upon re-installing the aggregation path hierarchy plugin, we are getting the following error:

`Exception in thread "main" java.lang.IllegalStateException: pathhierarchy-aggregation requires Java 17:, your system: 11`

Like the error states, we have Java 11, which is the latest version the Enterprise Elasticsearch supports:
![Screen Shot 2022-05-11 at 3 53 04 PM](https://user-images.githubusercontent.com/8472718/167947838-6a8ae696-4da2-4d92-bd56-152bb3c4bbd9.png)

Is it possible to release the plugin as Java 11 compatible?

**Comment by 5k4nd** [comment]
Hi @nescalera,

thanks for using our plugin. You will find a 7.17.1.0 version built with Java 11 here: https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/tag/v7.17.1.0-java11

Let me now if it solves your issue

**Comment by nescalera** [comment]
Thank you!
