### ISSUE TITLE
7.17.6 version not compatible with Java 11

### ISSUE THREAD

**Issue by bsherman101** [opendatasoft/elasticsearch-aggregation-pathhierarchy#28]
Hi,

We are upgrading our Elastic to 7.17.6 and when installing the plugin it complains that we need Java 15.  Your ReadMe claims the plugin is compatible with Java 11.

Any chance you can provide a build for 7.17.6 for Java 11?

Thank you.

**Comment by 5k4nd** [comment]
Hello!

Thank you for using our plugin, and sorry for the response delay.

The plugin _could_ be built for Java 11, but we are building it for ourselves, hence Java 17.
I just released a Java 11 release though, please see [here](https://github.com/opendatasoft/elasticsearch-aggregation-pathhierarchy/releases/tag/v7.17.6.0-java11).

Have a nice day
