### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by jprante** [opendatasoft/elasticsearch-aggregation-pathhierarchy#3]
This aggregation plugins looks like a good solution for one of my outstanding challenges, counting occurrences of millions of hierarchical bibliographic fields. Thank you!

Can I copy and modify your code? What is the license?

**Comment by clement-tourriere** [comment]
Hi @jprante, this plugin is under MIT license, you can, copy, modify or do whatever you want with the code ;). I will put the License file very soon.

**Comment by jprante** [comment]
Thanks! 

My version is at https://github.com/jprante/elasticsearch-aggregations/tree/1.5

Do you have plans to support Elasticsearch 2.x? I played with it, but failed miserably yet ... 

https://github.com/jprante/elasticsearch-aggregations/tree/master
