### ISSUE TITLE
ES 8.x Support

### ISSUE THREAD

**Issue by nicenatalia** [opendatasoft/elasticsearch-aggregation-pathhierarchy#31]
Hi,

The current 7.17.x version will soon reach EOL (https://www.elastic.co/support/eol), are there any plans to support the latest 8.x version?

Regards,
Natalia

**Comment by 5k4nd** [comment]
Hi @nicenatalia,

Unfortunately, we do not plan to support 8.x at the moment. We may do so in the future, but we cannot guarantee it or provide an expected date.
However, this plugin is fully open source, so feel free to open a pull request and we'll be happy to review your code!

Best regards,
