### ISSUE TITLE
Not ported to ES 2.x

### ISSUE THREAD

**Issue by kutenai** [opendatasoft/elasticsearch-aggregation-pathhierarchy#5]
This module is pretty important to our current flow, but it does not work under Elastic search release 2.x

I'm not really up to the task of porting it. I was wondering if there are any plans for this, or is there an alternative that anyone is aware of?

What would be involved in upgrading this to 2.x?

**Comment by kevitra** [comment]
I am also looking to use this plugin in 2.x (specifically 2.3.3).  Does anyone know of a good alternative?

**Comment by teebu** [comment]
try https://github.com/jprante/elasticsearch-aggregations been using it for a while now (es 2)

**Comment by clement-tourriere** [comment]
It is now ported on es 6.X. It will not be ported on elasticsearch < 6
